### ISSUE TITLE
Integrate cost-benefit models Python code into GI Evaluator/DataWolf workflows

### ISSUE THREAD

**Issue by selimnairb** [ResearchSoftwareInstitute/ginotebook#12]
- 75 percent complete

If you  are this task's owner, select the pencil icon in the upper right of this box to edit and increase this percent periodically as you make progress on this task (don't change the _\* nn percent complete_ formatting though). This value will be automatically propagated to the [GI Venture Dashboard](http://distribution.hydroshare.org/rayi/giventure/) below.

[CLICK HERE FOR THE GI VENTURE %COMPLETE DASHBOARD VIEW OF ALL TASKS](http://distribution.hydroshare.org/rayi/giventure/) 

---

**Comment by selimnairb** [comment]
Can use static results as mock-up for Sept. demo.

**Comment by selimnairb** [comment]
@BardiaHeidari Please update the percent complete of this issue (and close the issue if it is 100%).  Also, please let me know where I can find a mock up of the human preference report as I will need it on Monday the 24th.

**Comment by BardiaHeidari** [comment]
The skeleton of performance report is %80 complete and will include the results of human preference score. The scores were calculated and reported by Ankit on 08/21 for raingarden scenario in DeadRun 5 watershed. The scores are given as a CSV file with discrete values, as scores of each piece of raingarden, and will be reported, on a scale of 5, in spider plots in GI performance report. They will be sent along with the complete GI performance report on Monday 24th.

**Comment by SammyRivera** [comment]
Here is a picture of the GI Performance (Plan B) muck-up progress. The webpage works by reading a set of csv that come out of the GI Benefits python scripts (so far only 3 csv's). As for the human preference report, it was concluded that for now it will be presented as a metric in the radar (spyder) plot, but that potentially in the future a separate report will be created and could include illustrative examples, perhaps to the point of putting the scores in a google maps and allowing people to zoom in to the google street view of those locations.

We expect to have the muck up populated with realistic values by Monday, and finish the "aesthetic appeal" sometime during next week. Additionally, an option to explore the variance in the data is available, but will only be included as part of the demo if there is data for it.

![screen shot 2015-08-21 at 12 29 48 pm](https://cloud.githubusercontent.com/assets/3780858/9414762/9138a7a0-4800-11e5-9f01-757525457259.png)

**Comment by BardiaHeidari** [comment]
We need to talk with Ankit and decide whether his results fits into GI report objectives, with current scope of his analysis.

**Comment by BardiaHeidari** [comment]
Cost-benefit assessment python script has been successfully implemented in Datawolf. Now, I am modifying the script to be able read flag from RHESSys runs and produce CSV files.

**Comment by BardiaHeidari** [comment]
Cost-benefit model is able to read flags from previous RHESSys runs and will produce several CSV files.

**Comment by BardiaHeidari** [comment]
We decided to exclude property value increase from the analysis and add energy saving potential to report, which means that the workflow and its associated python scripts have to be changed significantly.
