### ISSUE TITLE
Add mock-up of report human-preference model report

### ISSUE THREAD

**Issue by selimnairb** [ResearchSoftwareInstitute/ginotebook#14]
- 100 percent complete

Sammy would integrate the scores on the HTML page.

If you  are this task's owner, select the pencil icon in the upper right of this box to edit and increase this percent periodically as you make progress on this task (don't change the _\* nn percent complete_ formatting though). This value will be automatically propagated to the [GI Venture Dashboard](http://distribution.hydroshare.org/rayi/giventure/) below.

[CLICK HERE FOR THE GI VENTURE %COMPLETE DASHBOARD VIEW OF ALL TASKS](http://distribution.hydroshare.org/rayi/giventure/) 

---

**Comment by AnkitRai** [comment]
Waiting for geolocations from  Bardia to run the model. Retraining of the Human Preference model is done.

**Comment by selimnairb** [comment]
@AnkitRai @BardiaHeidari Please update the status of this issue.  I will need this mockup on Monday August 24th to put together the integrated demo app for the August 26 code freeze.

**Comment by SammyRivera** [comment]
Here is a picture of the GI Performance (Plan B) muck-up progress. The webpage works by reading a set of csv that come out of the GI Benefits python scripts (so far only 3 csv's). As for the human preference report, it was concluded that for now it will be presented as a metric in the radar (spider) plot, but that potentially in the future a separate report will be created and could include illustrative examples, perhaps to the point of putting the scores in a google maps and allowing people to zoom in to the google street view of those locations.

We expect to have the muck up populated with realistic values by Monday, and finish the "aesthetic appeal" sometime during next week. Additionally, an option to explore the variance in the data is available, but will only be included as part of the demo if there is data for it.

![screen shot 2015-08-21 at 12 29 48 pm](https://cloud.githubusercontent.com/assets/3780858/9414762/9138a7a0-4800-11e5-9f01-757525457259.png)
