### ISSUE TITLE
Consider storing GI Instance polygons in UTM instead of WGS84

### ISSUE THREAD

**Issue by selimnairb** [ResearchSoftwareInstitute/ginotebook#17]
Our GI Elements are very small (~3-m+) compared to the precision afforded by WGS84 coordinates, which are in units of geodetic degrees.  Thus, we may experience positioning errors when GI Instance polygons are rendered, particularly in Street View, but perhaps also in the Bird View.  If this is a problem, we should try storing GI Instance polygons in UTM coordinates, which are in units of meters.

**Comment by jonglee1** [comment]
We need to know UTM projection information for each watershed that we are planning to support. The projection information can be included in the GeoJson of the watershed polygon.

**Comment by selimnairb** [comment]
We don't immediately need to do this so closing this issue for now.
