### ISSUE TITLE
Develop GI evaluator back-end

### ISSUE THREAD

**Issue by selimnairb** [ResearchSoftwareInstitute/ginotebook#25]
Develop GI Notebook and/or DataWolf back-end to allow GI scenarios to be evaluated according to performance models (hydrologic, cost, human preference, etc).

**Comment by jonglee1** [comment]
The RHESsys models for different watershed needs to be tested via DataWolf workflow and available computing resources. The concern is the running time of each RHESsys model for each watershed.
