### ISSUE TITLE
Fix authentication: use Basic authentication with SSL

### ISSUE THREAD

**Issue by selimnairb** [ResearchSoftwareInstitute/ginotebook#4]
- 100 percent complete

If you  are this task's owner, select the pencil icon in the upper right of this box to edit and increase this percent periodically as you make progress on this task (don't change the _\* nn percent complete_ formatting though). This value will be automatically propagated to the [GI Venture Dashboard](http://distribution.hydroshare.org/rayi/giventure/) below.

[CLICK HERE FOR THE GI VENTURE %COMPLETE DASHBOARD VIEW OF ALL TASKS](http://distribution.hydroshare.org/rayi/giventure/) 

---

This is optional for the Sept. demo

**Comment by mjstealey** [comment]
Per discussion with @selimnairb this task is frozen until after the September demo.

**Comment by mjstealey** [comment]
Task completed
