### ISSUE TITLE
Allow user to select climate base station file to use when running RHESSys in DataWolf workfows

### ISSUE THREAD

**Issue by selimnairb** [ResearchSoftwareInstitute/ginotebook#44]
- Climate base station files are in the "clim" sub-directory of a RHESSys model.  The base station files end in ".base".  The filename (before .base) should be displayed on a dropdown, and the user should be required to choose one.
- The .base file to use for a simulation is specified in the "world.hdr" file (or world file header) in the "world" sub-directory of a RHESSys model.  Simply copy the existing default header to a new file (the default header for a world file has the same name as the worldfile, but with .hdr appended), substituting the chosen climate base station for the default.
- To run the model with the specified climate base station add the "-whdr" command line option to RHESSys.  See [here](https://github.com/RHESSys/RHESSys_docker/blob/master/run.py#L217) for an example.

**Comment by selimnairb** [comment]
@navarroc Let me know if this needs more specification.  Thanks.

**Comment by selimnairb** [comment]
@navarroc Please let us know of the progress on this.  Moving milestone for now.  Please close when finished.  Thanks.

**Comment by navarroc** [comment]
This is done. I have a workflow that I provided @indira1026 that takes a climate base station input to the workflow and looks for the associated climate base station file in /clim and modifies the worldfile header. We may need to figure out how to populate the web UI with available climate base stations, but that should be a separate issue.
