### ISSUE TITLE
Specify input/output of GI converter

### ISSUE THREAD

**Issue by selimnairb** [ResearchSoftwareInstitute/ginotebook#50]
Outputs will be fed into co-benefits model.

**Comment by BardiaHeidari** [comment]
Datasets I need to get access to :
1: tiff file containing location of GI, e.g. raingarden_actual_gras.tiff 
2: tiff file containing landcover,i.e. landcover.tiff
3: tiff file showing subbasins boundaries.

**Comment by BardiaHeidari** [comment]
These are important parameters that we need to call for GIDB inside from datawolf workflow:
1: Life span of a raingardens
2: Financial interest rate
3: minimum construction cost for a raingarden
4: maximum construction cost for a raingarden
5: Pre-construction cost/ actual construction cost for a raingarden
6: intermittent cost/ construction cost for a raingarden
7: minimum maintenance cost for a raingarden
8: maximum maintenance cost for a raingarden
9: Life span of a tree
10: minimum construction cost for a tree
11: maximum construction cost for tree
12: Pre-construction cost/ actual construction cost for a tree
13: intermittent cost/ construction cost for a tree
14: minimum maintenance cost for a tree
15: maximum maintenance cost for a tree
16: Life span of a greenroof
17: minimum construction cost for a greenroof
18: maximum construction cost for greenroof
19: Pre-construction cost/ actual construction cost for a greenroof
20: intermittent cost/ construction cost for a greenroof
21: minimum maintenance cost for a greenroof
22: maximum maintenance cost for a greenroof

**Comment by BardiaHeidari** [comment]
We decided to extract some of the parameters used inside cost-benefit assessment model from GIDB instead of datawolf data management system, since it will be better to expose them to users and let them modify the parameters.

**Comment by selimnairb** [comment]
The schema for storing run information in GIDB is handled in #59
