### ISSUE TITLE
GI report format modification  

### ISSUE THREAD

**Issue by BardiaHeidari** [ResearchSoftwareInstitute/ginotebook#54]

**Comment by BardiaHeidari** [comment]
We decided to drop the property value increase side of co-benefit assessment out, since it is uncertain and is controversial. In other words it relies heavily on sales statistics and do not pass highly credible economic evaluations.

**Comment by BardiaHeidari** [comment]
Addition of Urban Heat Island mitigation effects to the co-benefit assessment models is another possibility. Sammy has conducted UHI mitigation assessment using ANN for Gwens Fall watershed. Bardia and Sammy will talk about the possibility.

**Comment by BardiaHeidari** [comment]
We decided to use spider plots as a platform to demonstrate difference in performance metric- i.e. environmental benefits, economic cost, and hydro logical performance. In other words, we want to allow users to see the effects of their designs. To do so, we need to keep a record of all workfows they have created and interactively compare them to each other.

**Comment by BardiaHeidari** [comment]
To facilitate communication of results to the users, we are going to modify units of some of the reported benefits. Here are some of the modifications:
1- Stormwater capture: will be reported both in mm and mm/household and mm/ piece of GI
2- Air quality uptake: will be reported in Ib/year and Ib/year/piece of GI

**Comment by selimnairb** [comment]
Storage of output results from a scenario run is summarized in #59.

**Comment by ArielKW** [comment]
We are adding peak flow from IUHM of both scenarios for 2-yr, 5-yr,10-yr, and 100-yr return period storms to report. The duration of the storms selected are still under discussion. I would suggest some duration like 2-hr and 24-hr for the storms we are looking at. 

Further discussion of which one of the peak flow (which frequency and duration) should be selected for the report.

**Comment by BardiaHeidari** [comment]
We decided to add pictures/ maps of the watershed inside the report for a more informative visualization of the design scenarios.

**Comment by BardiaHeidari** [comment]
We decided to provide more descriptions on the titles shown inside the tables.

**Comment by BardiaHeidari** [comment]
There is a need for better clarity on design scenario specifics, including footprint and number of GI.

**Comment by BardiaHeidari** [comment]
We need to add per treated impervious area into the titles.

**Comment by BardiaHeidari** [comment]
Using i-Tree methodologies, we need to extract empirical equations to estimate residential energy savings.

**Comment by BardiaHeidari** [comment]
We need to add another page inside the report citing references and explaining methodologies, especially for qualitative benefits.

**Comment by BardiaHeidari** [comment]
Scenario that are going ot be compared to each other will be selected under a UI discussed under #64.

**Comment by BardiaHeidari** [comment]
We need to change some of the cost units from millions to thousands.
