### ISSUE TITLE
Export Leaf Area Index from RHESSys into cost-benefit (under issue #50)

### ISSUE THREAD

**Issue by BardiaHeidari** [ResearchSoftwareInstitute/ginotebook#62]
This is part of issue #50

**Comment by BardiaHeidari** [comment]
@selimnairb We need to decide on possibility of spatial and temporal LAI export from RHESSys. It will be great if you can check on RHESSys LAI outputs to see whether having LAI results at watershed scale at monthly or yearly time frames will be feasible.

**Comment by selimnairb** [comment]
@BardiaHeidari Let me know what spatial and temporal aggregation of LAI data you need, and I will figure out what is possible, and what is easy.  Thanks.

**Comment by BardiaHeidari** [comment]
@selimnairb Spatial scale should be at watershed level; since we are comparing scenarios' performances at that scale. 
We can use yearly time-scales. However, since in real-world we can not expect GI to be maintained the way RHESSys treats it, having monthly scale or even seasonal scale will be more informative. 
Let me know if this isn't the answer to your questions, and whether it is feasible to have LAI results at mentioned scales. Thanks!

**Comment by selimnairb** [comment]
@BardiaHeidari This is helpful, thanks.

**Comment by selimnairb** [comment]
Given that we are currently only running RHESSys with static vegetation, the LAI map can simply be taken from the LAI input, which is available as a raster map in the GRASS dataset associated with a given watershed model.
