### ISSUE TITLE
RHESSys parameter input for DataWolf

### ISSUE THREAD

**Issue by whitton1212** [ResearchSoftwareInstitute/ginotebook#66]
List of parameters and their type
associate the min/max for each, granularity?
UI for setting these before a run

LATER: copy last parameter set into fields

**Comment by selimnairb** [comment]
The -s option can take 2 or 3 parameters, with the first two being required:

`-s m k z`

m = Decay of lateral saturated hydraulic conductivity with depth (multiplier)

> Range: 0.01 - 20.0

k = Lateral saturated hydraulic conductivity (multiplier)

> Range: 1.0 - 150.0

z = Soil depth (value in units of meters)

> Range: 0.1 - 10.0

The -sv option takes 2 parameters:

`-sv m k`

m = Decay of vertical saturated hydraulic conductivity with depth (multiplier)

> Range: 0.01 - 20.0

k = Vertical saturated hydraulic conductivity (multiplier)

> Range: 1.0 - 150.0

The -gw option takes 2 parameters:

`-gw gw1 gw2`

gw1 = Proportion of temporary surface water storage that bypasses the soil column and is added directly to ground water storage

> Range: 0.001 - 0.3

gw2 = Proportion of ground water storage that contributes to hill slope stream flow during each model time step

> Range: 0.01 - 0.9

**Comment by selimnairb** [comment]
@indira1026 @navarroc I've added the default parameter ranges for RHESSys sensitivity parameters.  See #66.

**Comment by selimnairb** [comment]
@indira1026 Here is the issue showing the parameter ranges.
