### ISSUE TITLE
Setup Delete and Edit functionality for instances

### ISSUE THREAD

**Issue by selimnairb** [ResearchSoftwareInstitute/ginotebook#7]
- 100 percent complete

If you  are this task's owner, select the pencil icon in the upper right of this box to edit and increase this percent periodically as you make progress on this task (don't change the _\* nn percent complete_ formatting though). This value will be automatically propagated to the [GI Venture Dashboard](http://distribution.hydroshare.org/rayi/giventure/) below.

[CLICK HERE FOR THE GI VENTURE %COMPLETE DASHBOARD VIEW OF ALL TASKS](http://distribution.hydroshare.org/rayi/giventure/) 

---

08/07/15: Delete functionality added

**Comment by rayi113** [comment]
* 40 percent complete

**Comment by selimnairb** [comment]
@indira1026 Has completed delete, and is working on edit.

**Comment by indira1026** [comment]
I have edit and delete ajax calls set up. But I am getting parsing issues with the response from ginotebook. 
The delete is currently returning nothing as a response. That is invalid JSON. @selimnairb  Can you add some sort of response to the delete calls in /gi_instances/id? 
I am still trying to debug why JQuery is unable to parse the response from the PUT call.

**Comment by indiragp** [comment]
Edit and Delete Functionality completed. 
I was having issues with ajax calls because I wasnt adding a '/' at the end of the url.

**Comment by selimnairb** [comment]
@indira1026 @jonglee1 Please close this issue if it is completed.
