### ISSUE TITLE
Adding SWMM modeling?

### ISSUE THREAD

**Issue by ArielKW** [ResearchSoftwareInstitute/ginotebook#72]
@BardiaHeidari Could you consider whether you want to add SWMM and write a GI converter for SWMM?

**Comment by BardiaHeidari** [comment]
Creating workflow for SWMM is feasible. 
If we can create GI converter for IUHM, we can possibly use it for SWMM as well.

**Comment by BardiaHeidari** [comment]
SWMM workflow is created for DeadRun 5. 
I am in the process of integrating cost-benefit model with SWMM input files.
