### ISSUE TITLE
Add ability to write GI instance polygons placed in streetview to GIDB via REST API

### ISSUE THREAD

**Issue by selimnairb** [ResearchSoftwareInstitute/ginotebook#9]
- 100 percent complete

If you  are this task's owner, select the pencil icon in the upper right of this box to edit and increase this percent periodically as you make progress on this task (don't change the _\* nn percent complete_ formatting though). This value will be automatically propagated to the [GI Venture Dashboard](http://distribution.hydroshare.org/rayi/giventure/) below.

[CLICK HERE FOR THE GI VENTURE %COMPLETE DASHBOARD VIEW OF ALL TASKS](http://distribution.hydroshare.org/rayi/giventure/) 

---

**Comment by selimnairb** [comment]
Major and minor axes added to GI element models in GIDB/GI Notebook.  For now we assume GI Elements are rectangular in shape.

**Comment by danweili** [comment]
treat both rain garden and trees as point features and use both major and minor axis length in lat and lng system.
